### ISSUE TITLE
Doesn't appear to work on Chrome 47.0

### ISSUE THREAD

**Issue by dhowe** [coreytegeler/add-art-chrome#12]
![screen shot 2015-12-20 at 1 00 48 am](https://cloud.githubusercontent.com/assets/737638/11914217/e122dc8c-a6b4-11e5-8926-73a01e295cc9.png)

**Comment by mushon** [comment]
Likewise.
Is the current version supposed to work "as advertised"?

**Comment by mushon** [comment]
Add art started working for me today. Not sure why. 
![image](https://cloud.githubusercontent.com/assets/27123/11995419/d6d2d60e-aa58-11e5-919f-ef1c57eedd4e.png)
It is still working/not-working on/off
but I can confirm seeing artworks replacing ads as seen ^

**Comment by owise1** [comment]
I think the issue here is simply that it doesn't catch all ads. see issue #10

**Comment by owise1** [comment]
try the latest version. I completely removed uBlock and now it's finding ads with a simple jQuery selector.  having much better results.
