### ISSUE TITLE
Created show not passing artAdder.verifyExhibition

### ISSUE THREAD

**Issue by coreytegeler** [coreytegeler/add-art-chrome#21]
Got the following in an email this morning:

> Any idea why this essay link:
> http://add-art.org/essays/?essay=abe3baff0d732c518c8304ac2d6be45e
> (created on the add-art.org site) would not work with your plugin in Chrome?
> It just says "there was a problem with that one..." when you attempt to add it.
> 
> That link has the following JSON at it:
> {"_id":"abe3baff0d732c518c8304ac2d6be45e",
> "_rev":"1-8bae2407cf808cd1ab707a4923433bca",
> "type":"exhibition"
> }

**Comment by owise1** [comment]
It looks like maybe it didn't save properly when it was created.  There are no works in this exhibition, or a title.... It would normally look something like this: https://github.com/owise1/addendum-exhibitions/blob/master/exhibitions.json
