### ISSUE TITLE
Host on RPi 

### ISSUE THREAD

**Issue by unclehowell** [coreytegeler/add-art-chrome#22]
Surely we can mod this to work on a pi hotspot. Surprised PiHole isn't making it a feature

**Comment by owise1** [comment]
That would be cool.  This plugin works by looking for recognized ad urls within the html of page then using javascript to replace them.   PiHole seems to work at the network level so I'm not sure how much of this project would be reusable, but maybe....

**Comment by unclehowell** [comment]
It appears this was born from a pihole hack, no?

**Comment by owise1** [comment]
no, i dont think so. it used to be based on a FireFox extension called AdBlockPlus

**Comment by unclehowell** [comment]
Thanks for setting me straight. Will definitely look into this. If we can replace the ads with ad units and sync to an open source ad manager, business would have a great proximity marketing solution
