### ISSUE TITLE
un-hardcode shows

### ISSUE THREAD

**Issue by owise1** [coreytegeler/add-art-chrome#3]
It looks like the shows are hardcoded in here (https://github.com/coreytegeler/add-art-chrome/blob/master/js/defaultSources.js), is there an external way to fetch the current shows?

**Comment by coreytegeler** [comment]
the way the plugin has worked is by hardcoding in the default shows, and allowing the user to add additional shows which I did not fully build in this chrome version

this hardcoded list is used to reach out to our wordpress (which i just invited you to) to fetch the RSS feeds that correspond to each show. we could drop the hardcoded list and instead request all WP posts on the site with a certain category, save them to local storage and populate the show selection interface with the results.

then when a user adds a new source that is not the default, we can append it to the local storage array of 
available sources

does this make sense?

**Comment by coreytegeler** [comment]
I'd also love to, at some point, build an interface for anyone to more easily create a show and publish it on the site for others to add

**Comment by owise1** [comment]
that makes sense. it looks like we can use this feed: http://add-art.org/feed/
