### ISSUE TITLE
Write build instructions in readme

### ISSUE THREAD

**Issue by slambert** [coreytegeler/add-art-chrome#8]
Maybe I should know this, but how do I make a build of the plugin to test?

**Comment by owise1** [comment]
here's how you test the unpacked version (i.e. this repo) https://developer.chrome.com/extensions/getstarted#unpacked.  This is useful for development and testing. When it's ready to be published to the chrome store there's a "pack extension" button

**Comment by slambert** [comment]
https://github.com/coreytegeler/add-art-chrome/commit/bd2f108007ee024ffd72f561ee7d5b6c081fe40a
