### ISSUE TITLE
Needs a default show

### ISSUE THREAD

**Issue by slambert** [coreytegeler/add-art-chrome#9]
Something should auto-download when you install. I installed and thought it wasn't working, but as soon as I chose art, it worked.

**Comment by owise1** [comment]
are you using the latest version in this repo?  I think this was a bug that's now fixed.  It should download a random exhibition when you install the plugin

**Comment by slambert** [comment]
Just tried it again. When I first install, I see ads. I restarted, just in case but no luck.

**Comment by owise1** [comment]
I just tested it on a fresh computer and it did automatically choose the most recent exhibition.  I've added notifications so it's clear what's going on.  Furthermore, it's on the chrome store now: https://chrome.google.com/webstore/detail/add-art/jplogjalofjlkendelkacpekloflkfeg

**Comment by slambert** [comment]
Woah - should we announce this, or wait til it's more ready. We don't want reviews before it's done, right?

**Comment by owise1** [comment]
You might want to talk to Joseph about the launch. I know he's working on stuff.

As far as functionality it's working pretty well now. I have it installed and it seems to catch most ads. Of course it's alway nice to have more features...
